manifest-el9-shared: apply dracut fix in postcript
This is a follow-up of [1], we have to apply the dracut fix here as
the new dracut release containing the same fix landed in F42 and EL10
repos. More details in [2][3]

[1] https://github.com/coreos/fedora-coreos-config/pull/3588
[2] https://github.com/coreos/fedora-coreos-tracker/issues/1937
[3] https://issues.redhat.com/browse/RHEL-87490

diff --git a/manifest-el9-shared.yaml b/manifest-el9-shared.yaml
--- a/manifest-el9-shared.yaml
+++ b/manifest-el9-shared.yaml
@@ -21,3 +21,12 @@ postprocess:
     #!/usr/bin/bash
     set -xeuo pipefail
     rm /usr/lib/systemd/zram-generator.conf
+
+  # We apply part of the patch https://github.com/dracut-ng/dracut-ng/pull/1306
+  # https://issues.redhat.com/browse/RHEL-87490
+  # https://github.com/coreos/fedora-coreos-tracker/issues/1937
+  # The script will start to fail once backported at distgit level signaling to remove it.
+  - |
+    #!/usr/bin/env bash
+    set -xeuo pipefail
+    sed -i '/^ExecStart=\/usr\/sbin\/mpathconf --enable$/,${s//ExecStart=\/usr\/sbin\/mpathconf --enable --user_friendly_names n/;b};$q1' /usr/lib/dracut/modules.d/90multipath/multipathd-configure.service
